/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.io.File;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elizabet
 */
public class ReporteView extends javax.swing.JPanel {

    /**
     * Creates new form ReporteView
     */
    public ReporteView() {
        initComponents();
        cbSucursalReporte.removeAllItems();
        cbSucursalReporte.addItem("Todas");
        cbSucursalReporte.addItem("Sucursal Centro");
        cbSucursalReporte.addItem("Sucursal Norte");
        cbSucursalReporte.addItem("Sucursal Sur");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSucursalReporte = new javax.swing.JLabel();
        cbSucursalReporte = new javax.swing.JComboBox<>();
        btnGenerar = new javax.swing.JButton();
        btnExportarCSV = new javax.swing.JButton();
        lblTotalPedidos = new javax.swing.JLabel();
        lblCancelados = new javax.swing.JLabel();
        lblTasa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductosTop = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        btnCerrarReporte = new javax.swing.JButton();

        lblSucursalReporte.setText("Sucursal:");

        cbSucursalReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnExportarCSV.setText("Exportar CSV");
        btnExportarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarCSVActionPerformed(evt);
            }
        });

        lblTotalPedidos.setText("Total pedidos:");

        lblCancelados.setText("Cancelados:");

        lblTasa.setText("Tasa cancelación:");

        tblProductosTop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Cantidad vendida"
            }
        ));
        jScrollPane1.setViewportView(tblProductosTop);

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnCerrarReporte.setText("Cerrar");
        btnCerrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrarReporte))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblCancelados)
                    .addComponent(lblTasa)
                    .addComponent(lblTotalPedidos)
                    .addComponent(lblSucursalReporte)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(btnExportarCSV))
                    .addComponent(cbSucursalReporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblSucursalReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSucursalReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnExportarCSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCancelados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTasa)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefrescar)
                    .addComponent(btnCerrarReporte))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarReporteActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarReporteActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        btnGenerarActionPerformed(evt);
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try {
            String sucursal = cbSucursalReporte.getSelectedItem().toString();

            // Datos temporales de prueba
            lblTotalPedidos.setText("Total pedidos: 0");
            lblCancelados.setText("Cancelados: 0");
            lblTasa.setText("Tasa cancelación: 0%");

            DefaultTableModel modelo
                    = (DefaultTableModel) tblProductosTop.getModel();

            modelo.setRowCount(0);

            JOptionPane.showMessageDialog(this,
                    "Reporte generado para la sucursal: " + sucursal);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al generar reporte: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnExportarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarCSVActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte CSV");
        int resultado = fileChooser.showSaveDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try (PrintWriter writer = new PrintWriter(archivo + ".csv")) {
                DefaultTableModel modelo
                        = (DefaultTableModel) tblProductosTop.getModel();
                // Encabezados
                for (int i = 0; i < modelo.getColumnCount(); i++) {
                    writer.print(modelo.getColumnName(i));
                    if (i < modelo.getColumnCount() - 1) {
                        writer.print(",");
                    }
                }
                writer.println();
                // Datos
                for (int fila = 0; fila < modelo.getRowCount(); fila++) {
                    for (int columna = 0;
                            columna < modelo.getColumnCount();
                            columna++) {
                        writer.print(modelo.getValueAt(fila, columna));
                        if (columna < modelo.getColumnCount() - 1) {
                            writer.print(",");
                        }
                    }
                    writer.println();
                }
                JOptionPane.showMessageDialog(this,
                        "Reporte exportado correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error al exportar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportarCSVActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarReporte;
    private javax.swing.JButton btnExportarCSV;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cbSucursalReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancelados;
    private javax.swing.JLabel lblSucursalReporte;
    private javax.swing.JLabel lblTasa;
    private javax.swing.JLabel lblTotalPedidos;
    private javax.swing.JTable tblProductosTop;
    // End of variables declaration//GEN-END:variables
}
