/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author leona
 */
public class LoginView extends javax.swing.JFrame {

    private String placeholder = "ej. admin";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana

        // Inicializa el placeholder
        jUsuarioText.setText(placeholder);
        jUsuarioText.setForeground(java.awt.Color.GRAY);

        // Esto quita el foco de la caja de texto y se lo pasa al botón
        jIngresar.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelAzul = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JLabel();
        jUsuarioText = new javax.swing.JTextField();
        jContraseña = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));

        jPanelAzul.setBackground(new java.awt.Color(0, 57, 93));
        jPanelAzul.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 350));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icono_seguridad.png"))); // NOI18N
        jLabel1.setText("Acceso al Sistema");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jUsuario.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 5, 60);
        jPanel1.add(jUsuario, gridBagConstraints);

        jUsuarioText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsuarioTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsuarioTextFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 60, 10, 60);
        jPanel1.add(jUsuarioText, gridBagConstraints);

        jContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jContraseña.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 5, 60);
        jPanel1.add(jContraseña, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 60, 10, 60);
        jPanel1.add(jPassword, gridBagConstraints);

        jIngresar.setText("Ingresar");
        jIngresar.setOpaque(true);
        jIngresar.setPreferredSize(new java.awt.Dimension(0, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 60, 10, 60);
        jPanel1.add(jIngresar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(40, 40, 40, 40);
        jPanelAzul.add(jPanel1, gridBagConstraints);

        getContentPane().add(jPanelAzul, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        jLabel1.setIconTextGap(10);
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jUsuarioTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsuarioTextFocusGained
        // Si el texto es igual al placeholder, lo limpia completamente
        if (jUsuarioText.getText().equals("ej. admin")) {
            jUsuarioText.setText("");
            jUsuarioText.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_jUsuarioTextFocusGained

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    private void jUsuarioTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsuarioTextFocusLost
        // Si al salir el campo está vacío, vuelve a poner el placeholder
        if (jUsuarioText.getText().trim().isEmpty()) {
            jUsuarioText.setText("ej. admin");
            jUsuarioText.setForeground(java.awt.Color.GRAY);
        }
    }//GEN-LAST:event_jUsuarioTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jContraseña;
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel jUsuario;
    private javax.swing.JTextField jUsuarioText;
    // End of variables declaration//GEN-END:variables
}
